name: Lint

permissions:
  contents: read

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Python environment
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38

      - name: flake8 Lint
        uses: py-actions/flake8@84ec6726560b6d5bd68f2a5bed83d62b52bb50ba

      - uses: psf/black@8a737e727ac5ab2f1d4cf5876720ed276dc8dc4b
        with:
          options: "--check --verbose"
          src: "zabbixci"
          use_pyproject: true