name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v4

      - name: Set up Python environment
        uses: actions/setup-python@v5

      - name: flake8 Lint
        uses: py-actions/flake8@v2

      - uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "zabbixci"
          use_pyproject: true